server:
  port: 8080
  servlet:
    context-path: "/shop"



spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: lhh123
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    timeout: 50

mybatis:
  mapper-locations: classpath:mapper/*.xml

